version: "3"

includes:
  module:
    taskfile: ./taskfiles.d/Module.yaml

tasks:
  default:
    silent: true
    cmds:
    - task --list

  build:
    desc: build the code
    vars:
      binary: ./bin/string
    cmds:
    - go build -o ./{{ .binary }}
    - ./{{ .binary }}
  test:
    desc: run the tests suite
    cmds:
    - |

      pkgx ginkgo run -v --cover ./src
