version: "3"

includes:
  module:
    taskfile: ./taskfiles.d/Module.yaml

tasks:
  default:
    silent: true
    cmds:
    - task --list

  build:
    desc: build the code
    cmds:
    - go build -o bin/boolean
    - ./bin/boolean

  test:
    desc: run the tests suite
    cmds:
    - |

      pkgx ginkgo run -v --cover ./src
